# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170120_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contraseña',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
