# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comentarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
